In [1]:
import pandas as pd
import numpy as np
import csv
import datetime 
import time

%matplotlib inline
import matplotlib.pyplot as plt 
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from src import settings

retail_rocket_root_path = settings.DATA_ROOT_PATH + '/site_data/retail_rocket/' 
recobell_root_path = settings.DATA_ROOT_PATH + "/site_data/recobell/"
ml_1m_root_path = settings.DATA_ROOT_PATH + "/site_data/ml-1m/"

In [2]:
ratings = pd.read_csv(ml_1m_root_path + 'raw_data/ratings.dat', delimiter='::', header=None, engine='python', names=['uid', 'itemid', 'rating', 'server_time'])
ratings.head()
# lay 5 gia tri tuong tac dau tien, moi tuong tac lay: uid, itemid, rating, server_time.

   uid  itemid  rating  server_time
0    1    1193       5    978300760
1    1     661       3    978302109
2    1     914       3    978301968
3    1    3408       4    978300275
4    1    2355       5    978824291

In [16]:
print(ratings.count())

uid            1000209
itemid         1000209
rating         1000209
server_time    1000209
dtype: int64

In [17]:
item_df = pd.read_csv(ml_1m_root_path + 'raw_data/movies.dat', delimiter='::', header=None, engine='python', names=['itemid', 'title', 'genres'])
item_df.head()

   itemid                               title                        genres
0       1                    Toy Story (1995)   Animation|Children's|Comedy
1       2                      Jumanji (1995)  Adventure|Children's|Fantasy
2       3             Grumpier Old Men (1995)                Comedy|Romance
3       4            Waiting to Exhale (1995)                  Comedy|Drama
4       5  Father of the Bride Part II (1995)                        Comedy

In [18]:
print(item_df.count())
print "\n"
new_list_item= item_df.loc[:,'itemid'].tolist()
print "Type data: ", type(new_list_item)
print "Length list item:", len(new_list_item)
print "Top 5 item:", new_list_item[:5]

itemid    3883
title     3883
genres    3883
dtype: int64


Type data:  <type 'list'>
Length list item: 3883
Top 5 item: [1, 2, 3, 4, 5]

In [19]:
print(ratings.count())

uid            1000209
itemid         1000209
rating         1000209
server_time    1000209
dtype: int64

In [20]:
# loai bo cac gia tri ratings trong bo du lieu ratings
# doi voi cac item_id co rating ma khong co trong danh sach cac item (dl sai).
new_rating = ratings[ratings.itemid.isin(item_df.loc[:, 'itemid'].tolist())]
print(new_rating.count())

uid            1000209
itemid         1000209
rating         1000209
server_time    1000209
dtype: int64

In [21]:
with open(ml_1m_root_path + 'i2index.txt') as f:
    for line in f:
        active_item_dict = {int(line.split(',')[0]): int(line.split(',')[1])}
        print (active_item_dict)

{1193: 0}
{661: 1}
{914: 2}
{3408: 3}
{2355: 4}
{1197: 5}
{1287: 6}
{2804: 7}
{594: 8}
{919: 9}
{595: 10}
{938: 11}
{2398: 12}
{2918: 13}
{1035: 14}
{2791: 15}
{2687: 16}
{2018: 17}
{3105: 18}
{2797: 19}
{2321: 20}
{720: 21}
{1270: 22}
{527: 23}
{2340: 24}
{48: 25}
{1097: 26}
{1721: 27}
{1545: 28}
{745: 29}
{2294: 30}
{3186: 31}
{1566: 32}
{588: 33}
{1907: 34}
{783: 35}
{1836: 36}
{1022: 37}
{2762: 38}
{150: 39}
{1: 40}
{1961: 41}
{1962: 42}
{2692: 43}
{260: 44}
{1028: 45}
{1029: 46}
{1207: 47}
{2028: 48}
{531: 49}
{3114: 50}
{608: 51}
{1246: 52}
{1357: 53}
{3068: 54}
{1537: 55}
{647: 56}
{2194: 57}
{648: 58}
{2268: 59}
{2628: 60}
{1103: 61}
{2916: 62}
{3468: 63}
{1210: 64}
{1792: 65}
{1687: 66}
{1213: 67}
{3578: 68}
{2881: 69}
{3030: 70}
{1217: 71}
{434: 72}
{2126: 73}
{3107: 74}
{3108: 75}
{3035: 76}
{1253: 77}
{1610: 78}
{292: 79}
{2236: 80}
{3071: 81}
{902: 82}
{368: 83}
{1259: 84}
{3147: 85}
{1544: 86}
{1293: 87}
{1188: 88}
{3255: 89}
{3256: 90}
{3257: 91}
{110: 92}
{2278: 93}
{2490: 94}
{1834: 95}
{3471: 96}
{589: 97}
{1690: 98}
{3654: 99}
{2852: 100}
{1945: 101}
{982: 102}
{1873: 103}
{2858: 104}
{1225: 105}
{515: 106}
{442: 107}
{2312: 108}
{265: 109}
{1408: 110}
{1084: 111}
{3699: 112}
{480: 113}
{1442: 114}
{2067: 115}
{1265: 116}
{1370: 117}
{1801: 118}
{1372: 119}
{2353: 120}
{3334: 121}
{2427: 122}
{590: 123}
{1196: 124}
{1552: 125}
{736: 126}
{1198: 127}
{593: 128}
{2359: 129}
{95: 130}
{2717: 131}
{2571: 132}
{1917: 133}
{2396: 134}
{3735: 135}
{1953: 136}
{1597: 137}
{3809: 138}
{1954: 139}
{1955: 140}
{235: 141}
{1124: 142}
{1957: 143}
{163: 144}
{21: 145}
{165: 146}
{1090: 147}
{380: 148}
{2501: 149}
{349: 150}
{457: 151}
{1096: 152}
{920: 153}
{459: 154}
{1527: 155}
{3418: 156}
{1385: 157}
{3451: 158}
{3095: 159}
{780: 160}
{498: 161}
{2728: 162}
{2002: 163}
{1784: 164}
{2943: 165}
{2006: 166}
{318: 167}
{1968: 168}
{3678: 169}
{1244: 170}
{356: 171}
{1245: 172}
{3893: 173}
{1247: 174}
{3421: 175}
{1641: 176}
{1394: 177}
{3534: 178}
{104: 179}
{2735: 180}
{1431: 181}
{3868: 182}
{1079: 183}
{2997: 184}
{1615: 185}
{1291: 186}
{653: 187}
{2167: 188}
{1580: 189}
{3619: 190}
{1049: 191}
{1261: 192}
{552: 193}
{1266: 194}
{733: 195}
{1378: 196}
{1379: 197}
{3552: 198}
{1304: 199}
{2470: 200}
{3168: 201}
{2617: 202}
{3671: 203}
{2871: 204}
{2115: 205}
{1136: 206}
{2081: 207}
{2951: 208}
{1214: 209}
{1036: 210}
{3702: 211}
{2366: 212}
{1387: 213}
{3527: 214}
{1201: 215}
{2947: 216}
{1240: 217}
{2987: 218}
{2333: 219}
{1175: 220}
{39: 221}
{288: 222}
{2337: 223}
{1535: 224}
{1392: 225}
{1466: 226}
{860: 227}
{1683: 228}
{866: 229}
{1684: 230}
{2770: 231}
{215: 232}
{1759: 233}
{501: 234}
{506: 235}
{1250: 236}
{3793: 237}
{509: 238}
{41: 239}
{2058: 240}
{3799: 241}
{47: 242}
{2700: 243}
{296: 244}
{581: 245}
{1617: 246}
{728: 247}
{299: 248}
{3079: 249}
{2560: 250}
{1909: 251}
{224: 252}
{3728: 253}
{229: 254}
{6: 255}
{3006: 256}
{1046: 257}
{800: 258}
{50: 259}
{52: 260}
{1191: 261}
{1192: 262}
{3081: 263}
{377: 264}
{1268: 265}
{3083: 266}
{3513: 267}
{2428: 268}
{2282: 269}
{3514: 270}
{1554: 271}
{1912: 272}
{2716: 273}
{1485: 274}
{2289: 275}
{162: 276}
{1127: 277}
{3016: 278}
{2070: 279}
{1704: 280}
{3163: 281}
{2437: 282}
{2291: 283}
{1635: 284}
{1279: 285}
{2721: 286}
{2723: 287}
{1921: 288}
{2725: 289}
{1923: 290}
{2580: 291}
{3386: 292}
{3744: 293}
{968: 294}
{896: 295}
{3020: 296}
{1788: 297}
{176: 298}
{461: 299}
{1429: 300}
{2159: 301}
{1715: 302}
{1643: 303}
{3249: 304}
{3176: 305}
{1719: 306}
{2806: 307}
{2734: 308}
{1649: 309}
{321: 310}
{2013: 311}
{3100: 312}
{2952: 313}
{1794: 314}
{2599: 315}
{1500: 316}
{2959: 317}
{1509: 318}
{1722: 319}
{1650: 320}
{908: 321}
{1653: 322}
{2384: 323}
{1729: 324}
{3476: 325}
{2890: 326}
{3113: 327}
{16: 328}
{2029: 329}
{194: 330}
{551: 331}
{1513: 332}
{3046: 333}
{2318: 334}
{1517: 335}
{1089: 336}
{3260: 337}
{913: 338}
{1730: 339}
{3409: 340}
{2607: 341}
{1449: 342}
{1732: 343}
{1733: 344}
{2390: 345}
{1734: 346}
{3266: 347}
{3267: 348}
{3624: 349}
{2395: 350}
{1594: 351}
{2683: 352}
{412: 353}
{2759: 354}
{994: 355}
{1884: 356}
{1885: 357}
{272: 358}
{24: 359}
{3051: 360}
{348: 361}
{2323: 362}
{1093: 363}
{29: 364}
{562: 365}
{1095: 366}
{1529: 367}
{2188: 368}
{497: 369}
{202: 370}
{1747: 371}
{2908: 372}
{1966: 373}
{3499: 374}
{353: 375}
{32: 376}
{1243: 377}
{1897: 378}
{1171: 379}
{3786: 380}
{34: 381}
{357: 382}
{36: 383}
{714: 384}
{2406: 385}
{1101: 386}
{3717: 387}
{1030: 388}
{1688: 389}
{364: 390}
{3501: 391}
{3072: 392}
{3074: 393}
{3508: 394}
{1043: 395}
{597: 396}
{383: 397}
{2506: 398}
{3524: 399}
{1569: 400}
{2082: 401}
{3600: 402}
{3604: 403}
{2802: 404}
{3536: 405}
{3753: 406}
{3682: 407}
{2017: 408}
{3685: 409}
{3610: 410}
{1296: 411}
{838: 412}
{1007: 413}
{1947: 414}
{2966: 415}
{266: 416}
{17: 417}
{1441: 418}
{1088: 419}
{912: 420}
{199: 421}
{1806: 422}
{2469: 423}
{2100: 424}
{1959: 425}
{1380: 426}
{569: 427}
{1674: 428}
{3565: 429}
{861: 430}
{1997: 431}
{1573: 432}
{474: 433}
{1221: 434}
{2336: 435}
{3425: 436}
{1393: 437}
{1682: 438}
{508: 439}
{3213: 440}
{42: 441}
{650: 442}
{3500: 443}
{3148: 444}
{2702: 445}
{1476: 446}
{1693: 447}
{151: 448}
{510: 449}
{4: 450}
{1621: 451}
{3155: 452}
{58: 453}
{2712: 454}
{2429: 455}
{1840: 456}
{1916: 457}
{1488: 458}
{230: 459}
{1120: 460}
{161: 461}
{1411: 462}
{524: 463}
{1059: 464}
{454: 465}
{1701: 466}
{1274: 467}
{741: 468}
{1277: 469}
{1639: 470}
{3528: 471}
{2297: 472}
{465: 473}
{1711: 474}
{538: 475}
{393: 476}
{2442: 477}
{73: 478}
{3246: 479}
{3173: 480}
{105: 481}
{253: 482}
{3250: 483}
{3252: 484}
{476: 485}
{111: 486}
{3259: 487}
{1589: 488}
{2023: 489}
{14: 490}
{337: 491}
{2314: 492}
{2600: 493}
{269: 494}
{555: 495}
{1660: 496}
{3265: 497}
{1735: 498}
{3481: 499}
{2686: 500}
{2688: 501}
{345: 502}
{2320: 503}
{25: 504}
{2324: 505}
{2329: 506}
{1810: 507}
{2541: 508}
{1673: 509}
{1678: 510}
{1027: 511}
{2699: 512}
{282: 513}
{367: 514}
{223: 515}
{3298: 516}
{3948: 517}
{805: 518}
{3510: 519}
{300: 520}
{1777: 521}
{3301: 522}
{1343: 523}
{3160: 524}
{529: 525}
{3452: 526}
{1060: 527}
{1356: 528}
{1358: 529}
{3178: 530}
{3751: 531}
{3826: 532}
{3755: 533}
{2302: 534}
{1148: 535}
{2166: 536}
{3253: 537}
{1584: 538}
{1223: 539}
{1446: 540}
{3623: 541}
{778: 542}
{1669: 543}
{3484: 544}
{3916: 545}
{1233: 546}
{1307: 547}
{3270: 548}
{1310: 549}
{428: 550}
{2622: 551}
{3358: 552}
{3359: 553}
{1756: 554}
{1320: 555}
{2124: 556}
{2125: 557}
{2054: 558}
{1252: 559}
{1254: 560}
{3869: 561}
{1256: 562}
{1257: 563}
{1831: 564}
{3363: 565}
{586: 566}
{587: 567}
{3438: 568}
{3439: 569}
{3296: 570}
{2496: 571}
{2497: 572}
{2: 573}
{2498: 574}
{153: 575}
{7: 576}
{2133: 577}
{2135: 578}
{2136: 579}
{2137: 580}
{802: 581}
{2138: 582}
{1409: 583}
{1339: 584}
{1269: 585}
{2640: 586}
{592: 587}
{596: 588}
{3447: 589}
{1918: 590}
{2140: 591}
{2072: 592}
{1271: 593}
{1345: 594}
{2077: 595}
{2078: 596}
{1276: 597}
{743: 598}
{671: 599}
{1278: 600}
{3525: 601}
{1927: 602}
{2657: 603}
{3388: 604}
{316: 605}
{317: 606}
{248: 607}
{2080: 608}
{1282: 609}
{1283: 610}
{750: 611}
{2087: 612}
{1286: 613}
{3608: 614}
{2662: 615}
{3466: 616}
{2300: 617}
{180: 618}
{329: 619}
{3034: 620}
{186: 621}
{2161: 622}
{3037: 623}
{2090: 624}
{3039: 625}
{2091: 626}
{830: 627}
{2093: 628}
{904: 629}
{2094: 630}
{1292: 631}
{2096: 632}
{1294: 633}
{765: 634}
{2746: 635}
{1009: 636}
{1948: 637}
{333: 638}
{339: 639}
{2316: 640}
{1371: 641}
{2174: 642}
{1374: 643}
{1375: 644}
{915: 645}
{1376: 646}
{1377: 647}
{916: 648}
{918: 649}
{1012: 650}
{2826: 651}
{3629: 652}
{1015: 653}
{1016: 654}
{1019: 655}
{3489: 656}
{344: 657}
{275: 658}
{2252: 659}
{277: 660}
{923: 661}
{924: 662}
{3701: 663}
{3703: 664}
{926: 665}
{3704: 666}
{1020: 667}
{784: 668}
{858: 669}
{1023: 670}
{1025: 671}
{2693: 672}
{1967: 673}
{351: 674}
{2405: 675}
{2407: 676}
{3066: 677}
{2193: 678}
{932: 679}
{1031: 680}
{1104: 681}
{1032: 682}
{435: 683}
{943: 684}
{3723: 685}
{1042: 686}
{370: 687}
{2423: 688}
{3153: 689}
{2424: 690}
{3086: 691}
{3087: 692}
{953: 693}
{954: 694}
{3591: 695}
{2863: 696}
{3593: 697}
{1125: 698}
{520: 699}
{3668: 700}
{2795: 701}
{1129: 702}
{2431: 703}
{62: 704}
{3309: 705}
{1633: 706}
{2436: 707}
{3097: 708}
{3099: 709}
{3812: 710}
{2000: 711}
{963: 712}
{2001: 713}
{1200: 714}
{2003: 715}
{1203: 716}
{2005: 717}
{1204: 718}
{969: 719}
{2872: 720}
{3675: 721}
{2946: 722}
{898: 723}
{2009: 724}
{2874: 725}
{899: 726}
{1135: 727}
{2948: 728}
{539: 729}
{2371: 730}
{3247: 731}
{3174: 732}
{3175: 733}
{2375: 734}
{2378: 735}
{971: 736}
{2011: 737}
{2012: 738}
{2015: 739}
{1215: 740}
{1073: 741}
{3688: 742}
{541: 743}
{542: 744}
{543: 745}
{3254: 746}
{2453: 747}
{2529: 748}
{1654: 749}
{1583: 750}
{3189: 751}
{116: 752}
{1586: 753}
{2021: 754}
{1220: 755}
{1080: 756}
{2967: 757}
{2968: 758}
{2530: 759}
{3264: 760}
{3194: 761}
{2393: 762}
{3198: 763}
{2399: 764}
{1302: 765}
{1230: 766}
{2105: 767}
{2033: 768}
{2108: 769}
{1234: 770}
{2109: 771}
{1091: 772}
{3347: 773}
{203: 774}
{1676: 775}
{208: 776}
{2111: 777}
{2040: 778}
{2041: 779}
{3928: 780}
{2043: 781}
{2045: 782}
{2046: 783}
{2047: 784}
{2049: 785}
{1753: 786}
{216: 787}
{2706: 788}
{2639: 789}
{2710: 790}
{663: 791}
{3448: 792}
{231: 793}
{2076: 794}
{246: 795}
{249: 796}
{1288: 797}
{3396: 798}
{3101: 799}
{2598: 800}
{2306: 801}
{764: 802}
{342: 803}
{1887: 804}
{2325: 805}
{3129: 806}
{2907: 807}
{788: 808}
{2766: 809}
{2335: 810}
{1461: 811}
{3146: 812}
{1546: 813}
{440: 814}
{441: 815}
{2507: 816}
{1563: 817}
{1498: 818}
{2883: 819}
{3182: 820}
{85: 821}
{88: 822}
{986: 823}
{481: 824}
{2539: 825}
{1665: 826}
{2106: 827}
{708: 828}
{3362: 829}
{813: 830}
{3897: 831}
{934: 832}
{3658: 833}
{1303: 834}
{999: 835}
{2616: 836}
{3785: 837}
{1331: 838}
{1262: 839}
{2641: 840}
{3036: 841}
{3479: 842}
{10: 843}
{2822: 844}
{3494: 845}
{421: 846}
{3070: 847}
{2414: 848}
{1479: 849}
{517: 850}
{952: 851}
{60: 852}
{3745: 853}
{2370: 854}
{1216: 855}
{2528: 856}
{1587: 857}
{3269: 858}
{3417: 859}
{3354: 860}
{1263: 861}
{2572: 862}
{2731: 863}
{3033: 864}
{2243: 865}
{2694: 866}
{2920: 867}
{1982: 868}
{2976: 869}
{2485: 870}
{141: 871}
{3798: 872}
{2707: 873}
{2567: 874}
{3004: 875}
{3005: 876}
{2719: 877}
{160: 878}
{748: 879}
{2724: 880}
{2581: 881}
{1783: 882}
{1422: 883}
{3461: 884}
{3535: 885}
{257: 886}
{832: 887}
{762: 888}
{2676: 889}
{1883: 890}
{2763: 891}
{3566: 892}
{2764: 893}
{1892: 894}
{1608: 895}
{1396: 896}
{2840: 897}
{2841: 898}
{3646: 899}
{500: 900}
{3145: 901}
{2272: 902}
{2273: 903}
{1619: 904}
{1625: 905}
{1487: 906}
{1702: 907}
{2433: 908}
{70: 909}
{1644: 910}
{1645: 911}
{2882: 912}
{2387: 913}
{2389: 914}
{2961: 915}
{553: 916}
{628: 917}
{3261: 918}
{2605: 919}
{1804: 920}
{1805: 921}
{2391: 922}
{2394: 923}
{3773: 924}
{1092: 925}
{1672: 926}
{2555: 927}
{2629: 928}
{2701: 929}
{2568: 930}
{2713: 931}
{1911: 932}
{3516: 933}
{2643: 934}
{2720: 935}
{2722: 936}
{2805: 937}
{2828: 938}
{2761: 939}
{2856: 940}
{2369: 941}
{2888: 942}
{2392: 943}
{2975: 944}
{1179: 945}
{2553: 946}
{2554: 947}
{3932: 948}
{3863: 949}
{1185: 950}
{3503: 951}
{3879: 952}
{3375: 953}
{1779: 954}
{164: 955}
{3457: 956}
{319: 957}
{247: 958}
{1428: 959}
{1284: 960}
{2660: 961}
{2661: 962}
{2663: 963}
{2664: 964}
{2667: 965}
{2668: 966}
{3032: 967}
{2311: 968}
{2173: 969}
{198: 970}
{2752: 971}
{340: 972}
{3700: 973}
{2901: 974}
{3638: 975}
{30: 976}
{1601: 977}
{3713: 978}
{2912: 979}
{3576: 980}
{503: 981}
{293: 982}
{1614: 983}
{2346: 984}
{942: 985}
{446: 986}
{1624: 987}
{3156: 988}
{2287: 989}
{2288: 990}
{3662: 991}
{3594: 992}
{3300: 993}
{1206: 994}
{1069: 995}
{76: 996}
{2377: 997}
{2010: 998}
{3827: 999}
{610: 1000}
{1077: 1001}
{2526: 1002}
{2527: 1003}
{2454: 1004}
{2455: 1005}
{3696: 1006}
{2533: 1007}
{1301: 1008}
{707: 1009}
{2613: 1010}
{2542: 1011}
{496: 1012}
{2549: 1013}
{1748: 1014}
{3927: 1015}
{2116: 1016}
{2117: 1017}
{2985: 1018}
{2989: 1019}
{2123: 1020}
{2052: 1021}
{2993: 1022}
{1186: 1023}
{222: 1024}
{158: 1025}
{3877: 1026}
{2139: 1027}
{3440: 1028}
{737: 1029}
{2718: 1030}
{2573: 1031}
{302: 1032}
{232: 1033}
{2141: 1034}
{2142: 1035}
{168: 1036}
{2143: 1037}
{2145: 1038}
{1344: 1039}
{3889: 1040}
{1275: 1041}
{3526: 1042}
{313: 1043}
{2153: 1044}
{2083: 1045}
{2085: 1046}
{2089: 1047}
{2807: 1048}
{2739: 1049}
{3397: 1050}
{3398: 1051}
{3399: 1052}
{327: 1053}
{1367: 1054}
{839: 1055}
{1005: 1056}
{405: 1057}
{1876: 1058}
{261: 1059}
{262: 1060}
{2248: 1061}
{1013: 1062}
{1882: 1063}
{1956: 1064}
{26: 1065}
{2253: 1066}
{3705: 1067}
{3633: 1068}
{3635: 1069}
{1960: 1070}
{3639: 1071}
{2402: 1072}
{2404: 1073}
{1606: 1074}
{1391: 1075}
{1033: 1076}
{291: 1077}
{44: 1078}
{2348: 1079}
{940: 1080}
{2421: 1081}
{2422: 1082}
{1126: 1083}
{1562: 1084}
{1499: 1085}
{1064: 1086}
{532: 1087}
{466: 1088}
{2373: 1089}
{2014: 1090}
{2953: 1091}
{2019: 1092}
{616: 1093}
{546: 1094}
{2450: 1095}
{475: 1096}
{86: 1097}
{2020: 1098}
{2025: 1099}
{2893: 1100}
{3698: 1101}
{485: 1102}
{1591: 1103}
{1739: 1104}
{3911: 1105}
{1094: 1106}
{493: 1107}
{2042: 1108}
{1242: 1109}
{3930: 1110}
{1321: 1111}
{2990: 1112}
{2991: 1113}
{1327: 1114}
{1258: 1115}
{2633: 1116}
{2638: 1117}
{1407: 1118}
{1334: 1119}
{2064: 1120}
{2644: 1121}
{2646: 1122}
{2647: 1123}
{2574: 1124}
{1772: 1125}
{2648: 1126}
{2649: 1127}
{1340: 1128}
{2653: 1129}
{1350: 1130}
{2160: 1131}
{330: 1132}
{1373: 1133}
{842: 1134}
{785: 1135}
{2836: 1136}
{420: 1137}
{3208: 1138}
{2338: 1139}
{2195: 1140}
{1974: 1141}
{879: 1142}
{2782: 1143}
{2789: 1144}
{3082: 1145}
{2860: 1146}
{2790: 1147}
{3596: 1148}
{1994: 1149}
{2502: 1150}
{2367: 1151}
{2296: 1152}
{2004: 1153}
{2949: 1154}
{1717: 1155}
{2376: 1156}
{3752: 1157}
{1219: 1158}
{3325: 1159}
{1655: 1160}
{2103: 1161}
{3273: 1162}
{1694: 1163}
{1468: 1164}
{585: 1165}
{3000: 1166}
{2800: 1167}
{3053: 1168}
{3268: 1169}
{3774: 1170}
{3355: 1171}
{1754: 1172}
{145: 1173}
{1689: 1174}
{2122: 1175}
{2134: 1176}
{1405: 1177}
{3017: 1178}
{1347: 1179}
{818: 1180}
{3450: 1181}
{678: 1182}
{312: 1183}
{173: 1184}
{2150: 1185}
{1425: 1186}
{3896: 1187}
{1799: 1188}
{256: 1189}
{185: 1190}
{2163: 1191}
{1438: 1192}
{833: 1193}
{2671: 1194}
{910: 1195}
{2249: 1196}
{771: 1197}
{849: 1198}
{3120: 1199}
{3052: 1200}
{2189: 1201}
{786: 1202}
{429: 1203}
{2263: 1204}
{2265: 1205}
{1034: 1206}
{798: 1207}
{799: 1208}
{1037: 1209}
{3210: 1210}
{2413: 1211}
{2416: 1212}
{1047: 1213}
{3660: 1214}
{3661: 1215}
{2792: 1216}
{1991: 1217}
{2794: 1218}
{65: 1219}
{1205: 1220}
{3243: 1221}
{2374: 1222}
{473: 1223}
{81: 1224}
{3258: 1225}
{112: 1226}
{3835: 1227}
{1222: 1228}
{3917: 1229}
{2478: 1230}
{1248: 1231}
{1249: 1232}
{3420: 1233}
{3505: 1234}
{1189: 1235}
{3507: 1236}
{3435: 1237}
{659: 1238}
{2202: 1239}
{1267: 1240}
{1199: 1241}
{2642: 1242}
{1845: 1243}
{3952: 1244}
{2148: 1245}
{2149: 1246}
{3521: 1247}
{674: 1248}
{2726: 1249}
{2808: 1250}
{3104: 1251}
{187: 1252}
{903: 1253}
{3618: 1254}
{3474: 1255}
{11: 1256}
{2241: 1257}
{3044: 1258}
{196: 1259}
{911: 1260}
{2176: 1261}
{3551: 1262}
{3556: 1263}
{1958: 1264}
{2322: 1265}
{2259: 1266}
{1388: 1267}
{3634: 1268}
{3708: 1269}
{1965: 1270}
{2409: 1271}
{2917: 1272}
{431: 1273}
{2410: 1274}
{2411: 1275}
{45: 1276}
{2419: 1277}
{951: 1278}
{521: 1279}
{3740: 1280}
{3741: 1281}
{2511: 1282}
{1212: 1283}
{1218: 1284}
{3763: 1285}
{1227: 1286}
{556: 1287}
{3338: 1288}
{125: 1289}
{3770: 1290}
{1306: 1291}
{2973: 1292}
{3920: 1293}
{1313: 1294}
{2118: 1295}
{2119: 1296}
{3424: 1297}
{3361: 1298}
{2132: 1299}
{303: 1300}
{2144: 1301}
{175: 1302}
{2301: 1303}
{2245: 1304}
{2757: 1305}
{3707: 1306}
{425: 1307}
{2915: 1308}
{372: 1309}
{2352: 1310}
{1057: 1311}
{468: 1312}
{1663: 1313}
{2709: 1314}
{157: 1315}
{1920: 1316}
{688: 1317}
{3676: 1318}
{3422: 1319}
{3423: 1320}
{719: 1321}
{3426: 1322}
{3287: 1323}
{2558: 1324}
{217: 1325}
{2053: 1326}
{2059: 1327}
{724: 1328}
{3502: 1329}
{3506: 1330}
{3360: 1331}
{1833: 1332}
{3: 1333}
{5: 1334}
{804: 1335}
{3441: 1336}
{234: 1337}
{236: 1338}
{237: 1339}
{2146: 1340}
{673: 1341}
{315: 1342}
{2154: 1343}
{1285: 1344}
{252: 1345}
{3614: 1346}
{1298: 1347}
{3543: 1348}
{1003: 1349}
{694: 1350}
{3040: 1351}
{2313: 1352}
{267: 1353}
{195: 1354}
{2247: 1355}
{1880: 1356}
{413: 1357}
{416: 1358}
{1888: 1359}
{276: 1360}
{278: 1361}
{3056: 1362}
{1381: 1363}
{1457: 1364}
{852: 1365}
{2906: 1366}
{1021: 1367}
{350: 1368}
{424: 1369}
{3130: 1370}
{2403: 1371}
{3206: 1372}
{3063: 1373}
{2261: 1374}
{38: 1375}
{2262: 1376}
{1463: 1377}
{1390: 1378}
{2266: 1379}
{2269: 1380}
{1100: 1381}
{432: 1382}
{2779: 1383}
{361: 1384}
{2412: 1385}
{1541: 1386}
{3219: 1387}
{2418: 1388}
{3584: 1389}
{511: 1390}
{518: 1391}
{445: 1392}
{2420: 1393}
{3152: 1394}
{378: 1395}
{1556: 1396}
{3590: 1397}
{450: 1398}
{2798: 1399}
{381: 1400}
{455: 1401}
{1703: 1402}
{3308: 1403}
{64: 1404}
{3098: 1405}
{2942: 1406}
{2875: 1407}
{605: 1408}
{609: 1409}
{463: 1410}
{1713: 1411}
{1640: 1412}
{467: 1413}
{74: 1414}
{3248: 1415}
{2447: 1416}
{2950: 1417}
{3684: 1418}
{3686: 1419}
{612: 1420}
{540: 1421}
{3689: 1422}
{471: 1423}
{472: 1424}
{2459: 1425}
{1588: 1426}
{118: 1427}
{3690: 1428}
{550: 1429}
{3331: 1430}
{3263: 1431}
{487: 1432}
{2463: 1433}
{94: 1434}
{122: 1435}
{1593: 1436}
{3846: 1437}
{491: 1438}
{3274: 1439}
{2473: 1440}
{499: 1441}
{207: 1442}
{135: 1443}
{1180: 1444}
{3364: 1445}
{2066: 1446}
{3469: 1447}
{905: 1448}
{922: 1449}
{2186: 1450}
{930: 1451}
{947: 1452}
{3730: 1453}
{955: 1454}
{528: 1455}
{3683: 1456}
{1237: 1457}
{2550: 1458}
{144: 1459}
{901: 1460}
{906: 1461}
{3548: 1462}
{334: 1463}
{846: 1464}
{928: 1465}
{1208: 1466}
{1224: 1467}
{3366: 1468}
{3370: 1469}
{1785: 1470}
{3102: 1471}
{3062: 1472}
{3726: 1473}
{2363: 1474}
{2944: 1475}
{3836: 1476}
{3769: 1477}
{1085: 1478}
{3405: 1479}
{2534: 1480}
{3197: 1481}
{494: 1482}
{1176: 1483}
{3943: 1484}
{3949: 1485}
{1922: 1486}
{3554: 1487}
{1041: 1488}
{1657: 1489}
{2544: 1490}
{2208: 1491}
{2065: 1492}
{3012: 1493}
{3022: 1494}
{3028: 1495}
{1281: 1496}
{3462: 1497}
{1937: 1498}
{1297: 1499}
{2747: 1500}
{921: 1501}
{3200: 1502}
{933: 1503}
{3640: 1504}
{1976: 1505}
{946: 1506}
{2922: 1507}
{2780: 1508}
{3088: 1509}
{957: 1510}
{2935: 1511}
{2936: 1512}
{3096: 1513}
{961: 1514}
{2870: 1515}
{3244: 1516}
{1235: 1517}
{3341: 1518}
{3349: 1519}
{3429: 1520}
{3286: 1521}
{28: 1522}
{3159: 1523}
{3821: 1524}
{3787: 1525}
{1680: 1526}
{3935: 1527}
{1183: 1528}
{3504: 1529}
{2637: 1530}
{2565: 1531}
{154: 1532}
{1699: 1533}
{2206: 1534}
{1333: 1535}
{3018: 1536}
{3019: 1537}
{2071: 1538}
{1272: 1539}
{1348: 1540}
{2650: 1541}
{2303: 1542}
{1295: 1543}
{907: 1544}
{1299: 1545}
{3546: 1546}
{2817: 1547}
{2674: 1548}
{1946: 1549}
{3110: 1550}
{3111: 1551}
{2178: 1552}
{1017: 1553}
{3121: 1554}
{2183: 1555}
{927: 1556}
{3498: 1557}
{3203: 1558}
{3204: 1559}
{1464: 1560}
{931: 1561}
{2344: 1562}
{2921: 1563}
{949: 1564}
{3727: 1565}
{2926: 1566}
{3587: 1567}
{3733: 1568}
{2932: 1569}
{2867: 1570}
{3599: 1571}
{3230: 1572}
{3167: 1573}
{3169: 1574}
{2941: 1575}
{1130: 1576}
{1061: 1577}
{3681: 1578}
{3760: 1579}
{3693: 1580}
{1152: 1581}
{1086: 1582}
{2467: 1583}
{1300: 1584}
{3844: 1585}
{1231: 1586}
{3340: 1587}
{2612: 1588}
{565: 1589}
{3271: 1590}
{2983: 1591}
{1835: 1592}
{3387: 1593}
{837: 1594}
{1895: 1595}
{3712: 1596}
{3597: 1597}
{2796: 1598}
{2432: 1599}
{2379: 1600}
{2380: 1601}
{2382: 1602}
{2383: 1603}
{2471: 1604}
{1251: 1605}
{2708: 1606}
{1760: 1607}
{3365: 1608}
{155: 1609}
{3871: 1610}
{803: 1611}
{1264: 1612}
{3512: 1613}
{2575: 1614}
{1419: 1615}
{824: 1616}
{2088: 1617}
{2732: 1618}
{3467: 1619}
{2238: 1620}
{2239: 1621}
{3473: 1622}
{3549: 1623}
{1949: 1624}
{2171: 1625}
{2682: 1626}
{3567: 1627}
{1964: 1628}
{3060: 1629}
{2331: 1630}
{3061: 1631}
{863: 1632}
{2919: 1633}
{3649: 1634}
{945: 1635}
{3725: 1636}
{948: 1637}
{3091: 1638}
{965: 1639}
{3320: 1640}
{1078: 1641}
{2385: 1642}
{3831: 1643}
{1081: 1644}
{2969: 1645}
{123: 1646}
{1162: 1647}
{2611: 1648}
{2474: 1649}
{3852: 1650}
{1172: 1651}
{3788: 1652}
{1827: 1653}
{233: 1654}
{172: 1655}
{178: 1656}
{2155: 1657}

{279: 2113}
{437: 2114}
{3724: 2115}
{3729: 2116}
{1050: 2117}
{3738: 2118}
{2939: 2119}
{451: 2120}
{2940: 2121}
{1209: 2122}
{78: 2123}
{79: 2124}
{82: 2125}
{1082: 2126}
{3841: 2127}
{1161: 2128}
{630: 2129}
{1099: 2130}
{3929: 2131}
{640: 2132}
{3007: 2133}
{3115: 2134}
{2505: 2135}
{1707: 2136}
{166: 2137}
{2596: 2138}
{2672: 2139}
{2678: 2140}
{1416: 2141}
{2913: 2142}
{9: 2143}
{2803: 2144}
{1919: 2145}
{637: 2146}
{973: 2147}
{1939: 2148}
{2929: 2149}
{3112: 2150}
{3069: 2151}
{1926: 2152}
{2690: 2153}
{2434: 2154}
{2439: 2155}
{1904: 2156}
{40: 2157}
{2995: 2158}
{43: 2159}
{2979: 2160}
{1187: 2161}
{3124: 2162}
{8: 2163}
{692: 2164}
{2170: 2165}
{2196: 2166}
{2448: 2167}
{990: 2168}
{2625: 2169}
{3444: 2170}
{240: 2171}
{1858: 2172}
{1004: 2173}
{2879: 2174}
{464: 2175}
{3767: 2176}
{3768: 2177}
{704: 2178}
{869: 2179}
{2357: 2180}
{577: 2181}
{801: 2182}
{2092: 2183}
{3054: 2184}
{1460: 2185}
{1551: 2186}
{2354: 2187}
{1489: 2188}
{885: 2189}
{1495: 2190}
{1582: 2191}
{3400: 2192}
{1592: 2193}
{2559: 2194}
{146: 2195}
{238: 2196}
{169: 2197}
{181: 2198}
{502: 2199}
{362: 2200}
{87: 2201}
{2899: 2202}
{558: 2203}
{700: 2204}
{2036: 2205}
{631: 2206}
{634: 2207}
{709: 2208}
{711: 2209}
{3946: 2210}
{3898: 2211}
{3710: 2212}
{536: 2213}
{3783: 2214}
{2771: 2215}
{1131: 2216}
{3282: 2217}
{2499: 2218}
{156: 2219}
{3606: 2220}
{1871: 2221}
{417: 2222}
{1024: 2223}
{298: 2224}
{72: 2225}
{84: 2226}
{2971: 2227}
{568: 2228}
{2873: 2229}
{2024: 2230}
{1178: 2231}
{1260: 2232}
{3093: 2233}
{2924: 2234}
{69: 2235}
{2519: 2236}
{2861: 2237}
{941: 2238}
{3324: 2239}
{3299: 2240}
{3825: 2241}
{3914: 2242}
{3859: 2243}
{754: 2244}
{3118: 2245}
{583: 2246}
{2157: 2247}
{826: 2248}
{2347: 2249}
{3384: 2250}
{438: 2251}
{1112: 2252}
{390: 2253}
{2927: 2254}
{2060: 2255}
{1437: 2256}
{2190: 2257}
{3141: 2258}
{2279: 2259}
{993: 2260}
{2582: 2261}
{12: 2262}
{294: 2263}
{373: 2264}
{63: 2265}
{2880: 2266}
{477: 2267}
{2073: 2268}
{1238: 2269}
{810: 2270}
{3895: 2271}
{2084: 2272}
{2169: 2273}
{1605: 2274}
{3225: 2275}
{1595: 2276}
{1750: 2277}
{2566: 2278}
{3515: 2279}
{2714: 2280}
{3453: 2281}
{3454: 2282}
{1881: 2283}
{2876: 2284}
{3824: 2285}
{2102: 2286}
{3776: 2287}
{2978: 2288}
{2048: 2289}
{667: 2290}
{1599: 2291}
{2476: 2292}
{204: 2293}
{1681: 2294}
{2818: 2295}
{3933: 2296}
{1349: 2297}
{3837: 2298}
{1542: 2299}
{2203: 2300}
{3870: 2301}
{2204: 2302}
{2210: 2303}
{1507: 2304}
{936: 2305}
{944: 2306}
{1596: 2307}
{1929: 2308}
{1936: 2309}
{1940: 2310}
{2904: 2311}
{3736: 2312}
{2937: 2313}
{1824: 2314}
{2938: 2315}
{3901: 2316}
{2535: 2317}
{3936: 2318}
{71: 2319}
{3791: 2320}
{3872: 2321}
{851: 2322}
{3177: 2323}
{3357: 2324}
{1755: 2325}
{3580: 2326}
{2877: 2327}
{3754: 2328}
{3915: 2329}
{2285: 2330}
{998: 2331}
{3029: 2332}
{1515: 2333}
{2181: 2334}
{1661: 2335}
{1925: 2336}
{1942: 2337}
{1167: 2338}
{3938: 2339}
{3913: 2340}
{3925: 2341}
{2098: 2342}
{2231: 2343}
{2280: 2344}
{1860: 2345}
{1325: 2346}
{2182: 2347}
{3883: 2348}
{3327: 2349}
{2099: 2350}
{3537: 2351}
{1995: 2352}
{2121: 2353}
{1322: 2354}
{1326: 2355}
{1328: 2356}
{1329: 2357}
{3941: 2358}
{3942: 2359}
{3013: 2360}
{2327: 2361}
{3138: 2362}
{2368: 2363}
{2515: 2364}
{2451: 2365}
{2525: 2366}
{3403: 2367}
{2634: 2368}
{2635: 2369}
{2645: 2370}
{2652: 2371}
{2736: 2372}
{2665: 2373}
{324: 2374}
{251: 2375}
{328: 2376}
{332: 2377}
{407: 2378}
{273: 2379}
{3491: 2380}
{3659: 2381}
{1987: 2382}
{1988: 2383}
{3806: 2384}
{1992: 2385}
{1128: 2386}
{1993: 2387}
{1996: 2388}
{1999: 2389}
{2878: 2390}
{606: 2391}
{2026: 2392}
{3840: 2393}
{3843: 2394}
{2104: 2395}
{3921: 2396}
{2113: 2397}
{892: 2398}
{241: 2399}
{3538: 2400}
{3934: 2401}
{742: 2402}
{3792: 2403}
{3001: 2404}
{3014: 2405}
{1355: 2406}
{687: 2407}
{2242: 2408}
{1389: 2409}
{2260: 2410}
{2267: 2411}
{3211: 2412}
{2343: 2413}
{875: 2414}
{3304: 2415}
{2518: 2416}
{101: 2417}
{2381: 2418}
{1807: 2419}
{2551: 2420}
{1841: 2421}
{3389: 2422}
{3465: 2423}
{2741: 2424}
{2745: 2425}
{2749: 2426}
{20: 2427}
{1890: 2428}
{3497: 2429}
{2928: 2430}
{2866: 2431}
{458: 2432}
{387: 2433}
{603: 2434}
{544: 2435}
{3766: 2436}
{3849: 2437}
{3125: 2438}
{1415: 2439}
{171: 2440}
{1879: 2441}
{1063: 2442}
{715: 2443}
{3865: 2444}
{3795: 2445}
{3150: 2446}
{2284: 2447}
{2561: 2448}
{1889: 2449}
{2769: 2450}
{3720: 2451}
{3822: 2452}
{3756: 2453}
{3857: 2454}
{3132: 2455}
{3073: 2456}
{3154: 2457}
{3311: 2458}
{1404: 2459}
{1439: 2460}
{1472: 2461}
{1647: 2462}
{1662: 2463}
{1053: 2464}
{384: 2465}
{2458: 2466}
{2654: 2467}
{1855: 2468}
{645: 2469}
{574: 2470}
{649: 2471}
{665: 2472}
{668: 2473}
{1354: 2474}
{781: 2475}
{1543: 2476}
{117: 2477}
{2609: 2478}
{3416: 2479}
{211: 2480}
{147: 2481}
{1900: 2482}
{306: 2483}
{1859: 2484}
{406: 2485}
{2696: 2486}
{2697: 2487}
{2925: 2488}
{3819: 2489}
{3746: 2490}
{535: 2491}
{627: 2492}
{97: 2493}
{2361: 2494}
{3064: 2495}
{129: 2496}
{1670: 2497}
{3579: 2498}
{3884: 2499}
{3719: 2500}
{512: 2501}
{548: 2502}
{1289: 2503}
{1454: 2504}
{793: 2505}
{3094: 2506}
{1780: 2507}
{1856: 2508}
{1932: 2509}
{3392: 2510}
{3395: 2511}
{1111: 2512}
{3813: 2513}
{549: 2514}
{2998: 2515}
{2360: 2516}
{213: 2517}
{206: 2518}
{2495: 2519}
{3539: 2520}
{3627: 2521}
{3679: 2522}
{1941: 2523}
{3801: 2524}
{3135: 2525}
{935: 2526}
{3292: 2527}
{3371: 2528}
{2570: 2529}
{2801: 2530}
{2862: 2531}
{3834: 2532}
{3853: 2533}
{3855: 2534}
{1194: 2535}
{760: 2536}
{1667: 2537}
{808: 2538}
{2086: 2539}
{2240: 2540}
{1445: 2541}
{3214: 2542}
{870: 2543}
{2626: 2544}
{3431: 2545}
{3432: 2546}
{3433: 2547}
{3434: 2548}
{2494: 2549}
{227: 2550}
{3385: 2551}
{3394: 2552}
{1008: 2553}
{408: 2554}
{338: 2555}
{426: 2556}
{3585: 2557}
{460: 2558}
{3117: 2559}
{1516: 2560}
{3055: 2561}
{787: 2562}
{3077: 2563}
{3192: 2564}
{3272: 2565}
{3275: 2566}
{2621: 2567}
{1910: 2568}
{308: 2569}
{2730: 2570}
{320: 2571}
{2594: 2572}
{2812: 2573}
{3625: 2574}
{3718: 2575}
{363: 2576}
{2859: 2577}
{1123: 2578}
{1055: 2579}
{1202: 2580}
{391: 2581}
{3903: 2582}
{3906: 2583}
{3858: 2584}
{759: 2585}
{3860: 2586}
{3950: 2587}
{1502: 2588}
{1539: 2589}
{1612: 2590}
{3302: 2591}
{1564: 2592}
{987: 2593}
{2482: 2594}
{1767: 2595}
{179: 2596}
{1896: 2597}
{3581: 2598}
{3598: 2599}
{68: 2600}
{3749: 2601}
{3823: 2602}
{2962: 2603}
{1236: 2604}
{638: 2605}
{325: 2606}
{274: 2607}
{1581: 2608}
{3415: 2609}
{3470: 2610}
{1273: 2611}
{2255: 2612}
{2295: 2613}
{3199: 2614}
{209: 2615}
{271: 2616}
{2905: 2617}
{352: 2618}
{2977: 2619}
{564: 2620}
{639: 2621}
{1812: 2622}
{1998: 2623}
{2988: 2624}
{2068: 2625}
{670: 2626}
{1361: 2627}
{2330: 2628}
{214: 2629}
{523: 2630}
{602: 2631}
{83: 2632}
{2022: 2633}
{809: 2634}
{1456: 2635}
{1604: 2636}
{1465: 2637}
{1473: 2638}
{1475: 2639}
{1497: 2640}
{2514: 2641}
{2516: 2642}
{1744: 2643}
{2548: 2644}
{1902: 2645}
{152: 2646}
{1771: 2647}
{1866: 2648}
{2597: 2649}
{1869: 2650}
{3709: 2651}
{2835: 2652}
{1119: 2653}
{479: 2654}
{2898: 2655}
{98: 2656}
{2974: 2657}
{3782: 2658}
{2996: 2659}
{1255: 2660}
{3520: 2661}
{2656: 2662}
{2666: 2663}
{3592: 2664}
{2035: 2665}
{3922: 2666}
{3924: 2667}
{831: 2668}
{1613: 2669}
{2504: 2670}
{2513: 2671}
{984: 2672}
{3401: 2673}
{3262: 2674}
{3673: 2675}
{3674: 2676}
{201: 2677}
{876: 2678}
{2372: 2679}
{3329: 2680}
{1728: 2681}
{1928: 2682}
{2587: 2683}
{1930: 2684}
{1933: 2685}
{255: 2686}
{1943: 2687}
{3475: 2688}
{1169: 2689}
{3002: 2690}
{669: 2691}
{3010: 2692}
{3951: 2693}
{1413: 2694}
{3885: 2695}
{680: 2696}
{3038: 2697}
{3047: 2698}
{2180: 2699}
{854: 2700}
{3075: 2701}
{2351: 2702}
{3235: 2703}
{1631: 2704}
{3090: 2705}
{3241: 2706}
{2512: 2707}
{2440: 2708}
{1572: 2709}
{970: 2710}
{3188: 2711}
{2488: 2712}
{2630: 2713}
{3379: 2714}
{2579: 2715}
{3456: 2716}
{2659: 2717}
{183: 2718}
{3547: 2719}
{2824: 2720}
{3559: 2721}
{2689: 2722}
{2830: 2723}
{3568: 2724}
{3731: 2725}
{2864: 2726}
{1132: 2727}
{1068: 2728}
{3680: 2729}
{99: 2730}
{2970: 2731}
{1232: 2732}
{3127: 2733}
{2271: 2734}
{3281: 2735}
{2590: 2736}
{1044: 2737}
{3041: 2738}
{3391: 2739}
{3715: 2740}
{3144: 2741}
{1825: 2742}
{31: 2743}
{1323: 2744}
{2475: 2745}
{3449: 2746}
{2552: 2747}
{573: 2748}
{2994: 2749}
{3008: 2750}
{685: 2751}
{3128: 2752}
{1397: 2753}
{1399: 2754}
{2276: 2755}
{1547: 2756}
{1482: 2757}
{1725: 2758}
{988: 2759}
{2610: 2760}
{1811: 2761}
{2479: 2762}
{2493: 2763}
{2711: 2764}
{301: 2765}
{2679: 2766}
{3711: 2767}
{369: 2768}
{57: 2769}
{388: 2770}
{613: 2771}
{2963: 2772}
{621: 2773}
{483: 2774}
{3839: 2775}
{409: 2776}
{1062: 2777}
{3886: 2778}
{761: 2779}
{1626: 2780}
{2614: 2781}
{504: 2782}
{3810: 2783}
{547: 2784}
{2894: 2785}
{776: 2786}
{137: 2787}
{3909: 2788}
{747: 2789}
{717: 2790}
{3867: 2791}
{3796: 2792}
{725: 2793}
{3031: 2794}
{2305: 2795}
{1503: 2796}
{767: 2797}
{774: 2798}
{2425: 2799}
{3158: 2800}
{3245: 2801}
{3181: 2802}
{2602: 2803}
{1741: 2804}
{2624: 2805}
{2483: 2806}
{1844: 2807}
{3459: 2808}
{2585: 2809}
{3532: 2810}
{1867: 2811}
{1795: 2812}
{1796: 2813}
{1891: 2814}
{2768: 2815}
{2844: 2816}
{1105: 2817}
{1058: 2818}
{525: 2819}
{67: 2820}
{80: 2821}
{3902: 2822}
{488: 2823}
{632: 2824}
{635: 2825}
{495: 2826}
{1646: 2827}
{1550: 2828}
{2445: 2829}
{27: 2830}
{295: 2831}
{3761: 2832}
{3162: 2833}
{1874: 2834}
{2865: 2835}
{1346: 2836}
{3180: 2837}
{1746: 2838}
{2651: 2839}
{1854: 2840}
{174: 2841}
{191: 2842}
{414: 2843}
{354: 2844}
{430: 2845}
{433: 2846}
{2889: 2847}
{710: 2848}
{1642: 2849}
{2589: 2850}
{2695: 2851}
{3945: 2852}
{2307: 2853}
{3165: 2854}
{3653: 2855}
{2129: 2856}
{3947: 2857}
{149: 2858}
{3149: 2859}
{2785: 2860}
{1427: 2861}
{917: 2862}
{1523: 2863}
{1531: 2864}
{2999: 2865}
{1410: 2866}
{2809: 2867}
{1317: 2868}
{2051: 2869}
{2151: 2870}
{3042: 2871}
{3043: 2872}
{3048: 2873}
{2345: 2874}
{2286: 2875}
{3161: 2876}
{964: 2877}
{102: 2878}
{119: 2879}
{131: 2880}
{3427: 2881}
{1839: 2882}
{1857: 2883}
{1863: 2884}
{3622: 2885}
{2685: 2886}
{3496: 2887}
{505: 2888}
{444: 2889}
{3804: 2890}
{537: 2891}
{3695: 2892}
{2031: 2893}
{2032: 2894}
{2900: 2895}
{1484: 2896}
{1076: 2897}
{570: 2898}
{662: 2899}
{1533: 2900}
{1471: 2901}
{877: 2902}
{3187: 2903}
{1585: 2904}
{1664: 2905}
{3343: 2906}
{263: 2907}
{3562: 2908}
{3716: 2909}
{1114: 2910}
{1150: 2911}
{2964: 2912}
{2062: 2913}
{3050: 2914}
{2569: 2915}
{3563: 2916}
{2839: 2917}
{3851: 2918}
{2075: 2919}
{3544: 2920}
{811: 2921}
{751: 2922}
{1508: 2923}
{3221: 2924}
{958: 2925}
{128: 2926}
{3577: 2927}
{2008: 2928}
{77: 2929}
{3830: 2930}
{2897: 2931}
{3854: 2932}
{250: 2933}
{1423: 2934}
{844: 2935}
{3215: 2936}
{3222: 2937}
{3171: 2938}
{3714: 2939}
{3586: 2940}
{3734: 2941}
{2704: 2942}
{1382: 2943}
{3139: 2944}
{2477: 2945}
{3367: 2946}
{2655: 2947}
{3487: 2948}
{2902: 2949}
{3732: 2950}
{210: 2951}
{2627: 2952}
{3667: 2953}
{1870: 2954}
{2751: 2955}
{1134: 2956}
{3765: 2957}
{3572: 2958}
{2799: 2959}
{619: 2960}
{2848: 2961}
{1598: 2962}
{3931: 2963}
{2992: 2964}
{1330: 2965}
{1335: 2966}
{3021: 2967}
{841: 2968}
{3058: 2969}
{3351: 2970}
{2636: 2971}
{2740: 2972}
{3488: 2973}
{2903: 2974}
{3573: 2975}
{2784: 2976}
{3833: 2977}
{3838: 2978}
{3692: 2979}
{2095: 2980}
{3339: 2981}
{2362: 2982}
{2388: 2983}
{3569: 2984}
{652: 2985}
{755: 2986}
{834: 2987}
{882: 2988}
{3345: 2989}
{2886: 2990}
{3777: 2991}
{1496: 2992}
{656: 2993}
{3119: 2994}
{3318: 2995}
{3335: 2996}
{3344: 2997}
{3346: 2998}
{2545: 2999}
{1743: 3000}
{1695: 3001}
{3490: 3002}
{3651: 3003}
{2855: 3004}
{1989: 3005}
{1990: 3006}
{2868: 3007}
{600: 3008}
{1165: 3009}
{1002: 3010}
{3372: 3011}
{840: 3012}
{865: 3013}
{867: 3014}
{2446: 3015}
{1679: 3016}
{1822: 3017}
{3531: 3018}
{3645: 3019}
{3669: 3020}
{1164: 3021}
{1362: 3022}
{3446: 3023}
{681: 3024}
{1332: 3025}
{2464: 3026}
{3276: 3027}
{3133: 3028}
{3310: 3029}
{3665: 3030}
{3781: 3031}
{1826: 3032}
{343: 3033}
{484: 3034}
{2219: 3035}
{2256: 3036}
{726: 3037}
{3106: 3038}
{2237: 3039}
{2521: 3040}
{2386: 3041}
{3289: 3042}
{3445: 3043}
{331: 3044}
{375: 3045}
{722: 3046}
{3894: 3047}
{1384: 3048}
{2673: 3049}
{2825: 3050}
{2843: 3051}
{1039: 3052}
{2933: 3053}
{1163: 3054}
{1525: 3055}
{3239: 3056}
{1490: 3057}
{3240: 3058}
{243: 3059}
{1798: 3060}
{470: 3061}
{1351: 3062}
{1511: 3063}
{2175: 3064}
{2281: 3065}
{2293: 3066}
{1651: 3067}
{3183: 3068}
{997: 3069}
{2620: 3070}
{1791: 3071}
{1006: 3072}
{335: 3073}
{422: 3074}
{75: 3075}
{2885: 3076}
{2400: 3077}
{1067: 3078}
{2733: 3079}
{1153: 3080}
{1383: 3081}
{2810: 3082}
{49: 3083}
{939: 3084}
{1817: 3085}
{1749: 3086}
{3670: 3087}
{124: 3088}
{1659: 3089}
{228: 3090}
{1773: 3091}
{2767: 3092}
{283: 3093}
{478: 3094}
{2298: 3095}
{881: 3096}
{3626: 3097}
{807: 3098}
{2055: 3099}
{2896: 3100}
{1906: 3101}
{96: 3102}
{1406: 3103}
{2063: 3104}
{3817: 3105}
{1149: 3106}
{1341: 3107}
{2465: 3108}
{2754: 3109}
{3637: 3110}
{2853: 3111}
{746: 3112}
{2618: 3113}
{3374: 3114}
{106: 3115}
{1809: 3116}
{1455: 3117}
{705: 3118}
{2715: 3119}
{1758: 3120}
{828: 3121}
{2837: 3122}
{626: 3123}
{1865: 3124}
{3739: 3125}
{2179: 3126}
{3293: 3127}
{3912: 3128}
{2074: 3129}
{1538: 3130}
{3790: 3131}
{3428: 3132}
{2847: 3133}
{2854: 3134}
{3832: 3135}
{3691: 3136}
{2128: 3137}
{1336: 3138}
{2326: 3139}
{2737: 3140}
{3721: 3141}
{2044: 3142}
{2982: 3143}
{2275: 3144}
{1837: 3145}
{1113: 3146}
{1133: 3147}
{347: 3148}
{1720: 3149}
{1440: 3150}
{578: 3151}
{3410: 3152}
{411: 3153}
{658: 3154}
{2931: 3155}
{2911: 3156}
{3892: 3157}
{3122: 3158}
{3143: 3159}
{3368: 3160}
{2481: 3161}
{2201: 3162}
{2342: 3163}
{1656: 3164}
{1312: 3165}
{1000: 3166}
{212: 3167}
{56: 3168}
{1412: 3169}
{462: 3170}
{121: 3171}
{3648: 3172}
{1893: 3173}
{716: 3174}
{2586: 3175}
{1579: 3176}
{2522: 3177}
{37: 3178}
{2487: 3179}
{3900: 3180}
{2056: 3181}
{2131: 3182}
{731: 3183}
{1447: 3184}
{2850: 3185}
{3805: 3186}
{1501: 3187}
{103: 3188}
{2778: 3189}
{1056: 3190}
{61: 3191}
{1903: 3192}
{2486: 3193}
{2834: 3194}
{200: 3195}
{270: 3196}
{1899: 3197}
{2158: 3198}
{3737: 3199}
{3875: 3200}
{1087: 3201}
{2743: 3202}
{114: 3203}
{3940: 3204}
{443: 3205}
{2211: 3206}
{2227: 3207}
{992: 3208}
{3291: 3209}
{3442: 3210}
{1853: 3211}
{2164: 3212}
{3313: 3213}
{2753: 3214}
{3632: 3215}
{3314: 3216}
{2658: 3217}
{3611: 3218}
{3878: 3219}
{888: 3220}
{1570: 3221}
{3759: 3222}
{3775: 3223}
{3848: 3224}
{402: 3225}
{3137: 3226}
{576: 3227}
{2631: 3228}
{297: 3229}
{1558: 3230}
{1565: 3231}
{3588: 3232}
{1549: 3233}
{1692: 3234}
{1168: 3235}
{2869: 3236}
{3862: 3237}
{3140: 3238}
{3944: 3239}
{2892: 3240}
{3866: 3241}
{3891: 3242}
{3899: 3243}
{1026: 3244}
{3025: 3245}
{3407: 3246}
{3463: 3247}
{1170: 3248}
{304: 3249}
{2452: 3250}
{2842: 3251}
{3223: 3252}
{1846: 3253}
{1567: 3254}
{136: 3255}
{3378: 3256}
{3232: 3257}
{1458: 3258}
{2466: 3259}
{2536: 3260}
{386: 3261}
{554: 3262}
{2200: 3263}
{850: 3264}
{545: 3265}
{1117: 3266}
{614: 3267}
{2577: 3268}
{167: 3269}
{2773: 3270}
{1040: 3271}
{385: 3272}
{3803: 3273}
{2593: 3274}
{2760: 3275}
{1696: 3276}
{2397: 3277}
{2756: 3278}
{3575: 3279}
{3845: 3280}
{3306: 3281}
{2207: 3282}
{1494: 3283}
{2509: 3284}
{3184: 3285}
{3647: 3286}
{2727: 3287}
{244: 3288}
{2304: 3289}
{2914: 3290}
{2960: 3291}
{2061: 3292}
{2317: 3293}
{2185: 3294}
{2187: 3295}
{1864: 3296}
{734: 3297}
{2215: 3298}
{1493: 3299}
{1829: 3300}
{2675: 3301}
{1151: 3302}
{2510: 3303}
{1793: 3304}
{3570: 3305}
{3026: 3306}
{2156: 3307}
{2251: 3308}
{3880: 3309}
{1668: 3310}
{1814: 3311}
{3495: 3312}
{1514: 3313}
{1561: 3314}
{3319: 3315}
{359: 3316}
{2945: 3317}
{310: 3318}
{925: 3319}
{1901: 3320}
{2578: 3321}
{59: 3322}
{3523: 3323}
{2283: 3324}
{2449: 3325}
{452: 3326}
{2244: 3327}
{397: 3328}
{2332: 3329}
{1575: 3330}
{756: 3331}
{2691: 3332}
{2813: 3333}
{2538: 3334}
{2191: 3335}
{792: 3336}
{3218: 3337}
{3402: 3338}
{3800: 3339}
{3850: 3340}
{3333: 3341}
{2981: 3342}
{821: 3343}
{220: 3344}
{1426: 3345}
{2350: 3346}
{2556: 3347}
{1144: 3348}
{2934: 3349}
{1622: 3350}
{1636: 3351}
{980: 3352}
{814: 3353}
{394: 3354}
{702: 3355}
{744: 3356}
{2246: 3357}
{1486: 3358}
{1154: 3359}
{1160: 3360}
{1504: 3361}
{2197: 3362}
{1574: 3363}
{33: 3364}
{3574: 3365}
{2775: 3366}
{389: 3367}
{1071: 3368}
{559: 3369}
{1671: 3370}
{3482: 3371}
{3126: 3372}
{1324: 3373}
{189: 3374}
{1174: 3375}
{1898: 3376}
{108: 3377}
{2758: 3378}
{3209: 3379}
{2192: 3380}
{1519: 3381}
{1098: 3382}
{1369: 3383}
{3151: 3384}
{1038: 3385}
{2923: 3386}
{3027: 3387}
{1433: 3388}
{3847: 3389}
{3757: 3390}
{3772: 3391}
{2257: 3392}
{3492: 3393}
{598: 3394}
{563: 3395}
{729: 3396}
{730: 3397}
{758: 3398}
{2233: 3399}
{2234: 3400}
{2441: 3401}
{245: 3402}
{1872: 3403}
{264: 3404}
{3636: 3405}
{1116: 3406}
{672: 3407}
{682: 3408}
{698: 3409}
{3116: 3410}
{862: 3411}
{2503: 3412}
{895: 3413}
{2557: 3414}
{2705: 3415}
{197: 3416}
{2765: 3417}
{53: 3418}
{526: 3419}
{90: 3420}
{567: 3421}
{962: 3422}
{618: 3423}
{2172: 3424}
{120: 3425}
{2209: 3426}
{703: 3427}
{3003: 3428}
{967: 3429}
{2814: 3430}
{2823: 3431}
{3486: 3432}
{3642: 3433}
{972: 3434}
{641: 3435}
{2608: 3436}
{1444: 3437}
{1850: 3438}
{3657: 3439}
{1138: 3440}
{2776: 3441}
{1436: 3442}
{769: 3443}
{985: 3444}
{1675: 3445}
{2576: 3446}
{3542: 3447}
{192: 3448}
{2127: 3449}
{887: 3450}
{712: 3451}
{2831: 3452}
{2358: 3453}
{1849: 3454}
{1121: 3455}
{1181: 3456}
{2562: 3457}
{3205: 3458}
{3644: 3459}
{401: 3460}
{2221: 3461}
{3131: 3462}
{3228: 3463}
{1315: 3464}
{864: 3465}
{219: 3466}
{3294: 3467}
{3305: 3468}
{3380: 3469}
{643: 3470}
{3419: 3471}
{2632: 3472}
{3888: 3473}
{823: 3474}
{2619: 3475}
{1877: 3476}
{3722: 3477}
{2101: 3478}
{2563: 3479}
{3905: 3480}
{853: 3481}
{3904: 3482}
{1548: 3483}
{1878: 3484}
{666: 3485}
{1360: 3486}
{1364: 3487}
{696: 3488}
{3517: 3489}
{2984: 3490}
{3601: 3491}
{3322: 3492}
{3303: 3493}
{3887: 3494}
{579: 3495}
{2235: 3496}
{789: 3497}
{796: 3498}
{3212: 3499}
{3216: 3500}
{2277: 3501}
{3220: 3502}
{1630: 3503}
{977: 3504}
{1652: 3505}
{2484: 3506}
{1852: 3507}
{3621: 3508}
{2821: 3509}
{3493: 3510}
{3641: 3511}
{1115: 3512}
{1118: 3513}
{601: 3514}
{3828: 3515}
{1142: 3516}
{1145: 3517}
{3687: 3518}
{2887: 3519}
{623: 3520}
{644: 3521}
{651: 3522}
{3876: 3523}
{660: 3524}
{1510: 3525}
{1386: 3526}
{859: 3527}
{3136: 3528}
{1553: 3529}
{3166: 3530}
{3312: 3531}
{1718: 3532}
{3321: 3533}
{142: 3534}
{1908: 3535}
{1764: 3536}
{2584: 3537}
{1787: 3538}
{2742: 3539}
{3778: 3540}
{3283: 3541}
{884: 3542}
{3085: 3543}
{1685: 3544}
{3748: 3545}
{1528: 3546}
{2591: 3547}
{3595: 3548}
{815: 3549}
{2254: 3550}
{2299: 3551}
{1520: 3552}
{775: 3553}
{1420: 3554}
{684: 3555}
{690: 3556}
{1534: 3557}
{3652: 3558}
{3277: 3559}
{3666: 3560}
{3522: 3561}
{3295: 3562}
{3377: 3563}
{557: 3564}
{1107: 3565}
{560: 3566}
{3458: 3567}
{706: 3568}
{2226: 3569}
{1815: 3570}
{2444: 3571}
{3353: 3572}
{3288: 3573}
{3352: 3574}
{1770: 3575}
{398: 3576}
{989: 3577}
{2783: 3578}
{1532: 3579}
{966: 3580}
{874: 3581}
{1886: 3582}
{2592: 3583}
{657: 3584}
{3890: 3585}
{2039: 3586}
{749: 3587}
{3818: 3588}
{582: 3589}
{642: 3590}
{3297: 3591}
{732: 3592}
{2930: 3593}
{3057: 3594}
{3472: 3595}
{130: 3596}
{139: 3597}
{2955: 3598}
{655: 3599}
{3485: 3600}
{790: 3601}
{1915: 3602}
{2833: 3603}
{1714: 3604}
{3207: 3605}
{3242: 3606}
{3533: 3607}
{1851: 3608}
{1830: 3609}
{3881: 3610}
{2777: 3611}
{3443: 3612}
{757: 3613}
{2895: 3614}
{889: 3615}
{1470: 3616}
{981: 3617}
{679: 3618}
{3373: 3619}
{872: 3620}
{3381: 3621}
{1555: 3622}
{3779: 3623}
{791: 3624}
{3609: 3625}
{1430: 3626}
{1724: 3627}
{2223: 3628}
{3233: 3629}
{3237: 3630}
{3762: 3631}
{3172: 3632}
{3065: 3633}
{3631: 3634}
{1139: 3635}
{3603: 3636}
{3842: 3637}
{572: 3638}
{2213: 3639}
{2217: 3640}
{3202: 3641}
{975: 3642}
{3376: 3643}
{311: 3644}
{1905: 3645}
{2258: 3646}
{2623: 3647}
{3236: 3648}
{396: 3649}
{868: 3650}
{3413: 3651}
{1316: 3652}
{878: 3653}
{226: 3654}
{2811: 3655}
{827: 3656}
{584: 3657}
{1820: 3658}
{607: 3659}
{701: 3660}
{2214: 3661}
{763: 3662}
{3229: 3663}
{820: 3664}
{3337: 3665}
{138: 3666}
{530: 3667}
{1070: 3668}
{843: 3669}
{3336: 3670}
{3460: 3671}
{3123: 3672}
{133: 3673}
{3290: 3674}
{1709: 3675}
{3164: 3676}
{3315: 3677}
{1832: 3678}
{439: 3679}
{134: 3680}
{2480: 3681}
{1842: 3682}
{2309: 3683}

In [22]:
with open(ml_1m_root_path + 'i2index.txt') as f:
    active_item_dict = {int(line.split(',')[0]): int(line.split(',')[1]) for line in f}

print(len(active_item_dict))
print (active_item_dict)
# item_df = item_df[item_df.itemid.isin(active_item_list)]
# item_df.count()

3706

In [9]:
genre_dict = {'Action': 0, 
              'Adventure': 1,
'Animation':2
, '''Children's''': 3
, 'Comedy': 4
, 'Crime': 5
, 'Documentary': 6
, 'Drama': 7
, 'Fantasy': 8
, 'Film-Noir': 9
, 'Horror': 10
, 'Musical': 11
, 'Mystery': 12
, 'Romance': 13
, 'Sci-Fi': 14
, 'Thriller': 15
, 'War': 16
, 'Western': 17}
genre_dict
# list category for list movie.

{'Action': 0,
 'Adventure': 1,
 'Animation': 2,
 "Children's": 3,
 'Comedy': 4,
 'Crime': 5,
 'Documentary': 6,
 'Drama': 7,
 'Fantasy': 8,
 'Film-Noir': 9,
 'Horror': 10,
 'Musical': 11,
 'Mystery': 12,
 'Romance': 13,
 'Sci-Fi': 14,
 'Thriller': 15,
 'War': 16,
 'Western': 17}

In [23]:
item_df.head()

   itemid                               title                        genres
0       1                    Toy Story (1995)   Animation|Children's|Comedy
1       2                      Jumanji (1995)  Adventure|Children's|Fantasy
2       3             Grumpier Old Men (1995)                Comedy|Romance
3       4            Waiting to Exhale (1995)                  Comedy|Drama
4       5  Father of the Bride Part II (1995)                        Comedy

In [33]:
# apply len tat cac cac phan tu cua item_df voi ham vo danh
y = item_df.apply(lambda x: [active_item_dict[x[0]], x[2]], axis=1, result_type='expand')
y.head()
# doi voi moi item trong item_df => thay id moi, categories
# 40,Animation|Children's|Comedy
# 573,Adventure|Children's|Fantasy
# 1333,Comedy|Romance
# 450,Comedy|Drama

KeyError: (51, u'occurred at index 50')

In [15]:
# write data frame into csv file
y.to_csv(ml_1m_root_path + 'i2pcat.txt', header=False, index=False)

# New task preprocessing for retail rocket dataset.

In [34]:
# events_df = pd.read_csv(retail_rocket_root_path + 'raw_data/events.csv')
# category_tree_df = pd.read_csv(retail_rocket_root_path + 'raw_data/category_tree.csv')

# item_properties file 
# 417 053 unique items
# every row in the file has corresponding timestamp
# item properties file contain timestamp column because all of them are time dependent
# since properties may change over time, e.g. price, category, etc

# value of categoryid properties contain item category identifier
# value of available properties contains availability of the item ( 1: available, 0: ow)
# All numerical values were marked with "n" char at the beginning, and have 3 digits precision after decimal point


item_properties_1_df = pd.read_csv(retail_rocket_root_path + 'raw_data/item_properties_part1.csv')
item_properties_2_df = pd.read_csv(retail_rocket_root_path + 'raw_data/item_properties_part2.csv')
# timestamp,itemid,property,value

# 1435460400000,460429,categoryid,1338
# 1441508400000,206783,888,1116713 960601 n277.200
# 1439089200000,395014,400,n552.000 639502 n720.000 424566
# 1431226800000,59481,790,n15360.000
# 1431831600000,156781,917,828513
# 1436065200000,285026,available,0
# 1434250800000,89534,213,1121373
# 1431831600000,264312,6,319724
# 1433646000000,229370,202,1330310
# 1434250800000,98113,451,1141052 n48.000
# 1439089200000,450113,888,1038400 45956 n504.000

In [35]:
item_properties_1_df[:11]

        timestamp  itemid    property                            value
0   1435460400000  460429  categoryid                             1338
1   1441508400000  206783         888          1116713 960601 n277.200
2   1439089200000  395014         400  n552.000 639502 n720.000 424566
3   1431226800000   59481         790                       n15360.000
4   1431831600000  156781         917                           828513
5   1436065200000  285026   available                                0
6   1434250800000   89534         213                          1121373
7   1431831600000  264312           6                           319724
8   1433646000000  229370         202                          1330310
9   1434250800000   98113         451                  1141052 n48.000
10  1439089200000  450113         888           1038400 45956 n504.000

In [17]:
item_properties_2_df[:11]

,timestamp,itemid,property,value
0,1433041200000,183478,561,769062
1,1439694000000,132256,976,n26.400 1135780
2,1435460400000,420307,921,1149317 1257525
3,1431831600000,403324,917,1204143
4,1435460400000,230701,521,769062
5,1433041200000,286407,202,820407
6,1438484400000,256368,888,437265 1296497 n24.000 229949 651738 285933
7,1437879600000,307534,888,150169 212349 1095303 824508 1257235 153900
8,1439089200000,102767,888,5135 790941 1055803 221748 122132 n12.000 1135...
9,1431831600000,215180,71,1096621
10,1435460400000,319117,202,876900

In [36]:
events_df = pd.read_csv(retail_rocket_root_path + 'raw_data/events.csv')
events_df.head()

       timestamp  visitorid event  itemid  transactionid
0  1433221332117     257597  view  355908            NaN
1  1433224214164     992329  view  248676            NaN
2  1433221999827     111016  view  318965            NaN
3  1433221955914     483717  view  253185            NaN
4  1433221337106     951259  view  367447            NaN

In [37]:
# loc function: access a group of row and columns by labels.

# item_properties_1_df.property: dua ra item_id va properties cua item_properties_1_df
# 0           categoryid
# 1                  888
# 2                  400
# 3                  790
# 4                  917

# item_properties_1_df.property == 'categoryid'
#  0            True
#  1           False
#  2           False
#  3           False
#  4           False
#  5           False
#  6           False

# item_properties_1_df.loc[item_properties_1_df.property == 'categoryid', ['timestamp', 'itemid', 'value']]

# lấy ở item_properties_1_df voi property = categoryid voi cac gia tri tren cac cot timestam, itemid va value

# giam gia tri tu 10999999 xuong con 426305 ban ghi

# Value of the "categoryid" property contains item category identifier.

item_cat_1 = item_properties_1_df.loc[item_properties_1_df.property == 'categoryid', ['timestamp', 'itemid', 'value']]
item_cat_1.head()

         timestamp  itemid value
0    1435460400000  460429  1338
140  1432436400000  281245  1277
151  1435460400000   35575  1059
189  1437274800000    8313  1147
197  1437879600000   55102    47

In [39]:
item_cat_2 = item_properties_2_df.loc[item_properties_2_df.property == 'categoryid', ['timestamp', 'itemid', 'value']]
item = item_cat_1.append(item_cat_2)
# y = item.drop_duplicates(['itemid', 'value']).groupby(['itemid', 'value']).count()
# y.head()
# # temp = item.loc[item.itemid == 25]
# # temp.sort_values(by=['timestamp'])
# # y = item.groupby(['itemid', 'value']).count()
# y.loc[y.timestamp == 1]
print "Record retrive from 1:", len(item_cat_1)
print "Record retrive from 1:", len(item_cat_2)
print "Total records:", len(item)

Record retrive from 1: 426305
Record retrive from 1: 361909
Total records: 788214

In [27]:
item[:10]

         timestamp  itemid value
0    1435460400000  460429  1338
140  1432436400000  281245  1277
151  1435460400000   35575  1059
189  1437274800000    8313  1147
197  1437879600000   55102    47
213  1433041200000  397079   619
237  1436670000000  265036  1228
254  1437879600000  124459  1277
310  1437879600000  350508   546
325  1439089200000  221365  1226

In [40]:
# y.loc[:, ['itemid', 'value']] # type: pd.DataFrame

# xoa cac ban ghi trung nhau tren cac cot item_id va value, va loc lai lay cac gia tri tren 2 cot itemid va value.
z = item.drop_duplicates(['itemid', 'value']).loc[:, ['itemid', 'value']]
print z.head()
print "\n"
print "Length of data after remove duplicate:", len(z)
# y.to_dict()
# z.to_csv(retail_rocket_root_path + 'temp.txt', index=False, header=False)

     itemid value
0    460429  1338
140  281245  1277
151   35575  1059
189    8313  1147
197   55102    47


Length of data after remove duplicate: 442432

# DEMO DROP_DUPLICATE.

In [37]:
raw_data = {'first_name': ['Jason', 'Jason', 'Jason','Tina', 'Jake', 'Amy'], 
        'last_name': ['Miller', 'Miller1', 'Miller2','Ali', 'Milner', 'Cooze'], 
        'age': [42, 42, 1111111, 36, 24, 73], 
        'preTestScore': [4, 4, 4, 31, 2, 3],
        'postTestScore': [25, 25, 25, 57, 62, 70]}
df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'preTestScore', 'postTestScore'])
print (df)

  first_name last_name      age  preTestScore  postTestScore
0      Jason    Miller       42             4             25
1      Jason   Miller1       42             4             25
2      Jason   Miller2  1111111             4             25
3       Tina       Ali       36            31             57
4       Jake    Milner       24             2             62
5        Amy     Cooze       73             3             70

In [38]:
df.drop_duplicates(['first_name'])

  first_name last_name  age  preTestScore  postTestScore
0      Jason    Miller   42             4             25
3       Tina       Ali   36            31             57
4       Jake    Milner   24             2             62
5        Amy     Cooze   73             3             70

In [39]:
df.drop_duplicates(['first_name','last_name'], keep='last') # xoa ban ghi giong nhau o ca first va last name.

  first_name last_name      age  preTestScore  postTestScore
0      Jason    Miller       42             4             25
1      Jason   Miller1       42             4             25
2      Jason   Miller2  1111111             4             25
3       Tina       Ali       36            31             57
4       Jake    Milner       24             2             62
5        Amy     Cooze       73             3             70

# END DEMO.

In [41]:
z.loc[z.itemid == 124]

Empty DataFrame
Columns: [itemid, value]
Index: []

In [41]:
# convert i2index.txt into dictionary
with open(retail_rocket_root_path + 'i2index.txt') as f: 
    active_item_dict = {int(line.split(',')[0]): int(line.split(',')[1]) for line in f}

# get list key from this dict.
active_item_list = active_item_dict.keys()

In [45]:
# remove cac phan tu trong z khong nam trong active item list (cac key lay tu file i2index.txt)
s = z[z.itemid.isin(active_item_list)]
# khong quan tam den value.
print 's head'
print s.head()

y = s.loc[:, 'itemid'].drop_duplicates() # xoa item_id trung nhau va loc tren cot itemid
print "y data type:",type(y)
print (y.head())
print len(y)

s head
     itemid value
189    8313  1147
408   96660   498
504  244437   438
804  313481  1613
836  366108   498
y data type: <class 'pandas.core.series.Series'>
189      8313
408     96660
504    244437
804    313481
836    366108
Name: itemid, dtype: int64
83274

In [43]:
# active item dict
print active_item_dict[75509]
print 'max key:', (max([int(s) for s in active_item_dict.keys()]))
print 'max value:',(max([int(s) for s in active_item_dict.values()]))

44419
max key: 466864
max value: 83273

In [46]:
# apply len tat ca cac phan tu cua s voi ham vo danh lambda.
# s.head()
#      itemid value
# 189    8313  1147
# 408   96660   498
# 504  244437   438
# 804  313481  1613
# 836  366108   498

# active item dict
# 393218: 27821,
#  393219: 30596,
#  393220: 2768,
#  152918: 36242,
#  6: 5054,

# thay the cac phan tu tung hang trong s tuong ung boi active_item_dict[x[0]], x[1]
# t moi thu duoc bao gom key cua active_item_dict va value cua s tuong ung.
t = s.apply(lambda x: [active_item_dict[x[0]], x[1]], axis=1, result_type='expand')
t.head()
# s.to_csv(retail_rocket_root_path + 'i2pcat.txt', index=False, header=False)

         0     1
189  75509  1147
408  42912   498
504  13362   438
804  33257  1613
836  60227   498

In [18]:
t.to_csv(retail_rocket_root_path + 'i2pcat.txt', index=False, header=False)
# i2pcat: item_id va categories tuong ung cua item do.
# voi item_id la id cu cua item khi chua mapping

In [33]:
print y.head() # y bao gom id cua ban ghi va tuong ung id item.
x = y.to_list() # lay cac item_id trong y
print len(x)
# print x[:5]

189      8313
408     96660
504    244437
804    313481
836    366108
Name: itemid, dtype: int64
83274

In [37]:
# get even_df tu trong danh sach cac events_df ma itemid do nam trong x
new_event_df = events_df[events_df.itemid.isin(x)]
# print(new_event_df.count())
# print(events_df.count())
new_event_df.to_csv(retail_rocket_root_path + 'raw_data/new_events.csv', index=False)
new_event_df.head()

       timestamp  visitorid event  itemid  transactionid
0  1433221332117     257597  view  355908            NaN
1  1433224214164     992329  view  248676            NaN
4  1433221337106     951259  view  367447            NaN
6  1433221923240     810725  view  443030            NaN
7  1433223291897     794181  view  439202            NaN

In [48]:
category_tree_df = pd.read_csv(retail_rocket_root_path + 'raw_data/category_tree.csv')
category_tree_df.head()

   categoryid  parentid
0        1016     213.0
1         809     169.0
2         570       9.0
3        1691     885.0
4         536    1691.0

In [40]:
category_tree_df['categoryid']

0       1016
1        809
2        570
3       1691
4        536
5        231
6        542
7       1146
8       1140
9       1479
10        83
11       688
12       257
13      1640
14       963
15       412
16       948
17       934
18       148
19        12
20      1459
21      1039
22       877
23        28
24       912
25       600
26       177
27       344
28       419
29       192
        ...
1639     628
1640    1020
1641    1248
1642    1500
1643    1317
1644     857
1645     551
1646    1343
1647     113
1648    1205
1649    1542
1650    1698
1651     760
1652     466
1653      72
1654    1095
1655     959
1656    1308
1657     679
1658     662
1659     460
1660     112
1661    1354
1662     486
1663     456
1664      49
1665    1112
1666    1336
1667     689
1668     761
Name: categoryid, Length: 1669, dtype: int64

In [49]:
# lay ra cac phan tu trong category_tree_df ma parent la na. ????
category_tree_df.loc[category_tree_df.parentid.isna()]

      categoryid  parentid
5            231       NaN
589          791       NaN
861         1490       NaN
939          431       NaN
1111         755       NaN
1142         378       NaN
1208        1579       NaN
1211        1394       NaN
1322         659       NaN
1329        1057       NaN
1375         859       NaN
1392         803       NaN
1395         250       NaN
1476        1452       NaN
1484        1182       NaN
1490        1692       NaN
1614        1600       NaN
1616        1482       NaN
1622        1224       NaN
1623        1532       NaN
1624         395       NaN
1628         653       NaN
1629         140       NaN
1650        1698       NaN
1657         679       NaN

# Below is recobell data preprocessing

# After that it change to retail_rocket data

In [4]:
print (ml_1m_root_path)
explicit_recobell_df = pd.read_csv(ml_1m_root_path + '_explicit.clean.txt', header=None, names=['uid', 'itemid', 'time', 'rating'])
print(explicit_recobell_df.head())
# active_item_df = pd.read_csv(recobell_root_path + 'item_repr.txt', header=None, names=['itemid', 'repr'], delimiter=',', quotechar='|', skiprows=1)
# active_item_df.head()

/home/tucng/Desktop/RS/project/src/site_data/ml-1m/
   uid  itemid       time  rating
0    1    1193  978300760       5
1    1    3408  978300275       4
2    1    2355  978824291       5
3    1    1287  978302039       5
4    1    2804  978300719       5

In [5]:
# load list key for i2index
with open(ml_1m_root_path + 'i2index.txt') as f:
    active_item_dict = {int(line.split(',')[0]): int(line.split(',')[1]) for line in f}
active_item_list = active_item_dict.keys()
print(len(active_item_list))

3706

In [6]:
# list key index from u2index.
with open(ml_1m_root_path + 'u2index.txt') as f:
    active_user_dict = {int(line.split(',')[0]): int(line.split(',')[1]) for line in f}
active_user_list = active_user_dict.keys()
print(len(active_user_list))

6040

In [7]:
# loai bo tuong tac ma user khong co trong active_user_list
explicit_recobell_df = explicit_recobell_df[explicit_recobell_df.uid.isin(active_user_list)]

# loai bo tuong tac ma item khong co trong active item list
explicit_recobell_df = explicit_recobell_df[explicit_recobell_df.itemid.isin(active_item_list)]

print 'explicit recobell df before:'
print (explicit_recobell_df.head())

# thay the rating ban dau boi user_id, item_id moi trong u2index va i2index.
explicit_recobell_df = explicit_recobell_df.apply(lambda x: [active_user_dict[x[0]], active_item_dict[x[1]]], axis=1, result_type='expand')
print(explicit_recobell_df.head())

explicit recobell df before:
   uid  itemid       time  rating
0    1    1193  978300760       5
1    1    3408  978300275       4
2    1    2355  978824291       5
3    1    1287  978302039       5
4    1    2804  978300719       5
   0  1
0  0  0
1  0  3
2  0  4
3  0  6
4  0  7

# user item explicit using for trainning

In [11]:
explicit_recobell_df.to_csv(ml_1m_root_path + 'ui_ex.txt', index=False, header=False)

# generate item representation.

In [9]:
# using item_repr.txt was made before to generate vector for this item.
active_item_df = pd.read_csv(recobell_root_path + 'item_repr.txt', header=None, names=['itemid', 'repr'], delimiter=',', quotechar='|', skiprows=1)
print(active_item_df.head())

   itemid                                               repr
0    3506  [[17, 0.25], [80, 0.25], [219, 0.25], [464, 0....
1    2293  [[16, 0.25], [46, 0.25], [335, 0.25], [1892, 0...
2    6555  [[9, 0.25], [83, 0.25], [153, 0.25], [1854, 0....
3    8448  [[6, 0.25], [82, 0.25], [249, 0.25], [832, 0.25]]
4    1818  [[1, 0.25], [38, 0.25], [286, 0.25], [841, 0.25]]
/home/tucng/Desktop/RS/project/src/site_data/recobell/

In [15]:
# make a dictionary for each item 
# each of element is a key of item and value of categories
item_repr_dict = {}
for _, row in active_item_df.iterrows():
    item_repr_dict[row[0]] = row[1]

print(item_repr_dict[0])
print(item_repr_dict[3506])

[[14, 0.25], [73, 0.25], [426, 0.25], [1620, 0.25]]
[[17, 0.25], [80, 0.25], [219, 0.25], [464, 0.25]]

In [17]:
explicit_recobell_df['num'] = 1

In [19]:
explicit_recobell_df.columns = ['uid', 'itemid', 'num']
explicit_recobell_df.head()

   uid  itemid  num
0    0       0    1
1    0       3    1
2    0       4    1
3    0       6    1
4    0       7    1

In [22]:
import json

def json_string_to_dense_vector(string_vector, dimensions):
    """
    Chuyen vector thua dang string: [[9, 0.010176822], [118, 0.010578092], [264, 0.020403702]]
    ve vector thuong K chieu cua numpy
    """
    K = dimensions

    vector = np.zeros(K, dtype=np.float32)
    if string_vector is None or len(string_vector) < 1:
        return vector

    x = json.loads(string_vector)
    
    for element in x:
        vector[element[0]] = element[1]
    return vector

In [23]:
def dense_vector_to_list_sparse_vector(vector):
    """
    Chuyen vector np ve vector thua dang string: [[9, 0.010176822], [118, 0.010578092], [264, 0.020403702]]
    """
    K = len(vector)
    threshold = 1e-6

    list_temp = []
    for i in range(0, K):
        if vector[i] > threshold:
            list_temp.append([i, float(vector[i])])
    return list_temp

In [24]:
def list_sparse_vector_to_json_string(sv):
    # type: (list) -> str
    """Convert vector in the form list of (int, float) to string

    Parameters
    ----------
    sv : list of (int, float)
        sparse_vector to be converted

    Examples
    ---------
    >>> sparse_vector = [(1, 0.123232), (2, 5.34234234)]
    >>> list_sparse_vector_to_json_string(sparse_vector)
    '[[1, 0.123232], [2, 5.34234234]]'
    """

    sum = 0
    list_sparse = []

    for item in sv:
        sum += item[1]

    for item in sv:
        list_sparse.append([int(item[0]), float(item[1] / sum)])

    return json.dumps(list_sparse)

In [ ]:
def add_avg()

In [27]:
explicit_recobell_df.head()

   uid  itemid  num
0    0       0    1
1    0       3    1
2    0       4    1
3    0       6    1
4    0       7    1

In [25]:
# apply into each row of explicit_recobell_df
t = explicit_recobell_df.apply(lambda x: [x[0], json_string_to_dense_vector([x[1]], 1939), x[2]], axis=1, result_type='expand').groupby(by=['0'])
print(t.head())

TypeError: ('expected string or buffer', u'occurred at index 0')

In [22]:
# item_recobell_df = pd.read_csv(recobell_root_path + 'raw_data/site_product.csv000', header=None, names=['itemid', 'price', 'cat1', 'cat2', 'cat3', 'cat4', 'brandid'])
# view_recobell_df = pd.read_csv(recobell_root_path + 'raw_data/tiny_site_view_log.csv000', header=None, names=['server_time', 'device', 'session_id', 'uid', 'itemid'])
order_recobell_df = pd.read_csv(recobell_root_path + 'raw_data/tiny_site_order_log.csv000', header=None, names=['server_time', 'device', 'session_id', 'uid', 'itemid', 'order_id', 'quantity'])
view_recobell_df.head()
# preprocessing with recobell datasets

               server_time device  session_id      uid   itemid
0  2016-08-13 12:38:47.512     MA  bgF9eb8ynC  b15f9e5  d9886b1
1   2016-08-14 13:41:34.30     MA  yzbfOf5b4e  8007201  e295b87
2  2016-08-14 13:37:57.682     MA  yzbfOf5b4e  8007201  cedc044
3  2016-08-11 19:04:41.939     MA  YBpaGQxzg3  99055ba  4f3ecec
4   2016-08-11 18:57:11.63     MA  YBpaGQxzg3  99055ba  ee3f827

In [3]:
item_recobell_df.nunique()

itemid     422516
price       24607
cat1           18
cat2           80
cat3          342
cat4         1499
brandid     10584
dtype: int64

In [18]:
active_item_df = pd.read_csv(recobell_root_path + 'item_repr.txt', header=None, names=['itemid', 'repr'], delimiter=',', quotechar='|')
active_item_df.head()

    itemid                                               repr
0  5919d61  [[17, 0.25], [80, 0.25], [219, 0.25], [464, 0....
1  1073c34  [[16, 0.25], [46, 0.25], [335, 0.25], [1892, 0...
2  559fc56  [[9, 0.25], [83, 0.25], [153, 0.25], [1854, 0....
3  67da1f9  [[6, 0.25], [82, 0.25], [249, 0.25], [832, 0.25]]
4  b5eaeaa  [[1, 0.25], [38, 0.25], [286, 0.25], [841, 0.25]]

In [33]:
z = active_item_df[active_item_df.itemid.isin(active_item_list)]
z = z.drop_duplicates(['itemid'])
z.count()

itemid    118293
repr      118293
dtype: int64

In [34]:
t = z.apply(lambda x: [active_item_dict[x[0]], x[1]], axis=1, result_type='expand')
t.head()

      0                                                  1
0  3506  [[17, 0.25], [80, 0.25], [219, 0.25], [464, 0....
1  2293  [[16, 0.25], [46, 0.25], [335, 0.25], [1892, 0...
2  6555  [[9, 0.25], [83, 0.25], [153, 0.25], [1854, 0....
3  8448  [[6, 0.25], [82, 0.25], [249, 0.25], [832, 0.25]]
4  1818  [[1, 0.25], [38, 0.25], [286, 0.25], [841, 0.25]]

In [37]:
import csv
t.to_csv(recobell_root_path + 'item_repr.txt', index=False, header=False, quotechar='|', quoting=csv.QUOTE_ALL)

In [28]:
y = active_item_df.loc[:, 'itemid'].drop_duplicates()
y.count()

422516

In [29]:
x = y.tolist()
print(len(x))

422516

In [30]:
new_view_df = view_recobell_df[view_recobell_df.itemid.isin(x)]
new_order_df = order_recobell_df[order_recobell_df.itemid.isin(x)]
new_view_df.count()

server_time    4521505
device         4521505
session_id     4521505
uid            4521505
itemid         4521505
dtype: int64

In [31]:
new_view_df.to_csv(recobell_root_path + 'raw_data/new_tiny_site_view_log.csv000', index=False, header=False)
new_order_df.to_csv(recobell_root_path + 'raw_data/new_tiny_site_order_log.csv000', index=False, header=False)

In [27]:
z.head()

    itemid                                               repr
0  5919d61  [[17, 0.25], [80, 0.25], [219, 0.25], [464, 0....
1  1073c34  [[16, 0.25], [46, 0.25], [335, 0.25], [1892, 0...
2  559fc56  [[9, 0.25], [83, 0.25], [153, 0.25], [1854, 0....
3  67da1f9  [[6, 0.25], [82, 0.25], [249, 0.25], [832, 0.25]]
4  b5eaeaa  [[1, 0.25], [38, 0.25], [286, 0.25], [841, 0.25]]

In [ ]:
z.to_csv(recobell_root_path + 'item_repr.txt', index=False, header=False)

In [61]:
a =  item_recobell_df.loc[:, ['cat2', 'cat3']]
x =  item_recobell_df.loc[:, ['cat2']]

In [63]:
y = a.drop_duplicates().groupby(['cat3']).count()
y.loc[y.cat2 > 1]

         cat2
cat3
0ea22c8     2
142a302     2
23bebb0     2
3919b77     2
44650a9     7
512f480     2
58961c3     2
5b889c3     2
7efeb2d     3
9ea0ca2     2
aaba489     7
ce186c5     2
dcbae73     2
fac1ca9     2

In [59]:
item_recobell_df[item_recobell_df.cat2 == 'bd0b0a5'].drop_duplicates(['cat1', 'cat2'])

         itemid  price     cat1     cat2     cat3     cat4  brandid
9       eb32384  67410  d9d0ba9  bd0b0a5  f1c99bd  af4f9f8  7a9f4fc
114195  257677b  39000  66dd73d  bd0b0a5  58961c3  a457db3  fd23080

In [38]:
b = set(item_recobell_df.cat1) | set(item_recobell_df.cat2) | set(item_recobell_df.cat3) | set(item_recobell_df.cat4)

In [39]:
len(b)

1838

In [10]:
c = list(set(item_recobell_df.cat1))

In [1]:
len(c)
c

NameError: name 'c' is not defined

# Pre-process for movielens data

In [3]:
ratings.head()

   uid  itemid  rating  server_time
0    1    1193       5    978300760
1    1     661       3    978302109
2    1     914       3    978301968
3    1    3408       4    978300275
4    1    2355       5    978824291

In [4]:
count_rating = ratings.groupby(['uid'])[['rating']].count()
count_rating[count_rating['rating'] < 20]

Empty DataFrame
Columns: [rating]
Index: []

In [5]:
mean_rating = ratings.groupby(['uid']).agg({'rating': 'mean'})
mean_rating['uid'] = mean_rating.index
mean_rating[mean_rating['rating'] < 2]

# ratings[ratings['uid'] == 2744]

        rating   uid
uid
2744  1.304348  2744
3598  1.015385  3598
4349  1.962963  4349
4486  1.058824  4486
4539  1.815126  4539
5334  1.927273  5334
5850  1.844828  5850

In [7]:
count_rating['rating'].max()

2314

In [8]:
count_rating['rating'].min()

20

In [48]:
mean_rating
with open(ml_1m_root_path + 'u2index.txt') as f:
    active_user_dict = {int(line.split(',')[0]): int(line.split(',')[1]) for line in f}
active_user_list = active_user_dict.keys()
print(len(active_user_list))
new_mean_rating = mean_rating.apply(lambda x: pd.Series([active_user_dict[x['uid']], x['rating']], index=['uid', 'rating']), axis=1)

6040

In [55]:
new_mean_rating['uid'] = new_mean_rating['uid'].apply(lambda x: int(x))

In [6]:
mean_rating.to_csv(ml_1m_root_path + 'user_mean_rating.txt', header=False, index=False, quotechar='|', quoting=csv.QUOTE_ALL)